/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miPaquete;

import javax.swing.JOptionPane;

/**
 *
 * @author leox01
 */
public class buscarVista extends javax.swing.JFrame {

    /**
     * Creates new form buscarVista
     */
    public buscarVista() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarButton = new javax.swing.JButton();
        codigoBuscadoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCarrera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSemestre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPromedio = new javax.swing.JTextField();
        eliminarButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        atrasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jTextFieldCodigo.setEnabled(false);

        jLabel2.setText("Nombre:");

        jTextFieldNombre.setToolTipText("");
        jTextFieldNombre.setEnabled(false);

        jLabel3.setText("Codigo:");

        jLabel5.setText("Carrera:");

        jTextFieldCarrera.setToolTipText("");
        jTextFieldCarrera.setEnabled(false);

        jLabel4.setText("Semestre:");

        jTextFieldSemestre.setEnabled(false);

        jLabel6.setText("Promedio:");

        jTextFieldPromedio.setEnabled(false);

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        atrasButton.setText("Atrás");
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigoBuscadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCarrera, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldSemestre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(atrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminarButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarButton)
                    .addComponent(codigoBuscadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atrasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        new VistaIncio().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_atrasButtonActionPerformed
    
    public static int mostrarMensajeEmergente(String titulo, String mensaje){
        Object[] options = { "Aceptar", "Cancelar" };
        int resultadoDeLaPregunta = -1;
        
        if(titulo.equals("ALERTA")){
            resultadoDeLaPregunta = JOptionPane.showOptionDialog(null, "¿Estas seguro de eliminar al Alumno?", "Alerta",JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, options, options[0]);
           
            if(resultadoDeLaPregunta == JOptionPane.YES_OPTION){
                  
                
                return resultadoDeLaPregunta;
                
            }else{
                
                mostrarMensajeEmergente("Mensaje", "No se eliminó el usuario");
            }
        
        
        }else
            JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.OK_OPTION);
        return  resultadoDeLaPregunta;
    }
    
    
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
      
        if(editButton.getText().equals("Editar")){
            jTextFieldCodigo.setEnabled(true);
            jTextFieldNombre.setEnabled(true);
            jTextFieldCarrera.setEnabled(true);
            jTextFieldPromedio.setEnabled(true);
            jTextFieldSemestre.setEnabled(true);
            repaint();
            editButton.setText("Aceptar Edición");
        }else{
            
            jTextFieldCodigo.setEnabled(false);
            jTextFieldNombre.setEnabled(false);
            jTextFieldCarrera.setEnabled(false);
            jTextFieldPromedio.setEnabled(false);
            jTextFieldSemestre.setEnabled(false);
            repaint();
            
            int codigo=0;
            int semestre=0;
            double promedio=0;
            String nombre = jTextFieldNombre.getText();
            String carrera = jTextFieldCarrera.getText();
            try {
                codigo = Integer.parseInt(jTextFieldCodigo.getText());
                semestre = Integer.parseInt(jTextFieldSemestre.getText());
                promedio = Double.parseDouble(jTextFieldPromedio.getText());

            } catch (Exception e) {
                System.out.println(e);
                System.out.println("Problema al convertir de String a int o double");
            }
            
            int codigoAlumnoEditar = Integer.parseInt(codigoBuscadoTextField.getText());
            
            Controlador.guardarAlumnoEditado(new Alumno(codigo, nombre, carrera, semestre, promedio),codigoAlumnoEditar);
            editButton.setText("Editar");
            mostrarMensajeEmergente("Editar", "Alumno Editado Exitosamente!!!");
            
        }
       
       
    }//GEN-LAST:event_editButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        
        
        if(!codigoBuscadoTextField.getText().equals("")){
            int codigoBuscado;
            try {
                
                codigoBuscado =  Integer.parseInt(codigoBuscadoTextField.getText());
                
                Alumno alumno = Controlador.buscarAlumno(codigoBuscado);
                
                if(alumno.getCodigo()!=-1){
                    //mostrar en la vista
                    jTextFieldCodigo.setText(Integer.toString(alumno.getCodigo()));
                    jTextFieldNombre.setText(alumno.getNombre());
                    jTextFieldCarrera.setText(alumno.getCarrera());
                    jTextFieldPromedio.setText(""+alumno.getPromedio());
                    jTextFieldSemestre.setText(""+alumno.getSemestre());
                    
                    
                }else{
                    mostrarMensajeEmergente("Buscar", "No se encontró el alumno");
                    jTextFieldCodigo.setText("");
                    jTextFieldCarrera.setText("");
                    jTextFieldNombre.setText("");
                    jTextFieldPromedio.setText("");
                    jTextFieldSemestre.setText("");
                    jTextFieldCodigo.setEnabled(false);
                    jTextFieldNombre.setEnabled(false);
                    jTextFieldCarrera.setEnabled(false);
                    jTextFieldPromedio.setEnabled(false);
                    jTextFieldSemestre.setEnabled(false);
                    editButton.setText("Editar");
                    repaint();
                }
                
                
            } catch (Exception e) {
                mostrarMensajeEmergente("Error", "El código debe de ser un número ");
            }
             
        }else{
            
            mostrarMensajeEmergente("Error", "Introduce un código para buscar");
        
        }
        
        
        
        
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        
          if(!codigoBuscadoTextField.getText().equals("")){
              int codigoAEliminar;
              
              try {
                  codigoAEliminar =  Integer.parseInt(codigoBuscadoTextField.getText());
                
                Alumno alumno = Controlador.buscarAlumno(codigoAEliminar);
                
                if(alumno.getCodigo()!=-1){
                    //mostrar en la vista
                    jTextFieldCodigo.setText(Integer.toString(alumno.getCodigo()));
                    jTextFieldNombre.setText(alumno.getNombre());
                    jTextFieldCarrera.setText(alumno.getCarrera());
                    jTextFieldPromedio.setText(""+alumno.getPromedio());
                    jTextFieldSemestre.setText(""+alumno.getSemestre());
                    
                    
                    int respuestaEliminarAlumno = mostrarMensajeEmergente("ALERTA", "¿Seguro que quieres eliminar el usuario?");
                    
                    if(respuestaEliminarAlumno==0){
                        if(Controlador.eliminarAlumno(codigoAEliminar)){
                        
                            mostrarMensajeEmergente("Mensaje", "Alumno Eliminado Exitosamente");
                            jTextFieldCodigo.setText("");
                            jTextFieldCarrera.setText("");
                            jTextFieldNombre.setText("");
                            jTextFieldPromedio.setText("");
                            jTextFieldSemestre.setText("");
                            jTextFieldCodigo.setEnabled(false);
                            jTextFieldNombre.setEnabled(false);
                            jTextFieldCarrera.setEnabled(false);
                            jTextFieldPromedio.setEnabled(false);
                            jTextFieldSemestre.setEnabled(false);
                            editButton.setText("Editar");
                            repaint();
                        }
                    }
                    
                    
                }else{
                    mostrarMensajeEmergente("Buscar", "No se encontró el alumno");
                    jTextFieldCodigo.setText("");
                    jTextFieldCarrera.setText("");
                    jTextFieldNombre.setText("");
                    jTextFieldPromedio.setText("");
                    jTextFieldSemestre.setText("");
                    jTextFieldCodigo.setEnabled(false);
                    jTextFieldNombre.setEnabled(false);
                    jTextFieldCarrera.setEnabled(false);
                    jTextFieldPromedio.setEnabled(false);
                    jTextFieldSemestre.setEnabled(false);
                    editButton.setText("Editar");
                    repaint();
                }
                  
              } catch (Exception e) {
                  mostrarMensajeEmergente("Error", "El código debe de ser un número ");
              }
          
          }else{
            
            mostrarMensajeEmergente("Error", "Introduce un código para Eliminar");
        
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField codigoBuscadoTextField;
    private javax.swing.JButton editButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldCarrera;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPromedio;
    private javax.swing.JTextField jTextFieldSemestre;
    // End of variables declaration//GEN-END:variables
}
