/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miPaquete;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author leox01
 */
public class vistaRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form vistaRegistrar
     */
    
    
    public String[] carreras = {"Ingeniería en negocios",
                            "Licenciatura en Administración",
                            "Licenciatura en Administración Financiera y Sistemas",
                            "Licenciatura en Contaduría Pública",
                            "Licenciatura en Economía",
                            "Licenciatura en Gestión de Negocios Gastronómicos",
                            "Licenciatura en Gestión y Economía Ambiental",
                            "Licenciatura en Mercadotecnia",
                            "Licenciatura en Negocios Internacionales",
                            "Licenciatura en Recursos Humanos",
                            "Licenciatura en Tecnologías de la información",
                            "Licenciatura en Turismo",
                            "Relaciones Públicas y Comunicación"};
    public vistaRegistrar() {
        initComponents();
        
        for (String carrera : carreras) {
            carrerasComboBox.addItem(carrera);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSemestre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPromedio = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        carrerasComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Alumno");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombre.setToolTipText("");
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 304, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Alumno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 430, -1));

        jTextFieldCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                revisarCodigoRepetido(evt);
            }
        });
        getContentPane().add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 304, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel3.setText("Codigo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel4.setText("Semestre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel5.setText("Carrera:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));
        getContentPane().add(jTextFieldSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 304, -1));

        jLabel6.setText("Promedio:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        getContentPane().add(jTextFieldPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 304, -1));

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 159, 53));

        jButtonAtras.setText("Atrás");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 83, 53));

        getContentPane().add(carrerasComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 304, 39));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miPaquete/background.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
      
       new VistaIncio().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
       //leer de la vista (TextFields)
        int codigo=0;
        int semestre=0;
        double promedio=0;
        String nombre = jTextFieldNombre.getText();
        int carreraIndex = carrerasComboBox.getSelectedIndex();
        String carrera = carreras[carreraIndex];
        try {
            codigo = Integer.parseInt(jTextFieldCodigo.getText());
            semestre = Integer.parseInt(jTextFieldSemestre.getText());
            promedio = Double.parseDouble(jTextFieldPromedio.getText());
       
        } catch (Exception e) {
            System.out.println(e);
            System.out.println("Problema al convertir de String a int o double");
        }
       //revisar que no estén en blanco las variables
       
       if(codigo!=0&&semestre!=0&&promedio!=0&&!carrera.equals("")&&!nombre.equals("")){
           //mandar a un método guardar 
            if(Controlador.registrarAlumno(codigo, nombre, carrera, semestre, promedio)){
                //mandar mensaje de registro exitoso
                mostrarMensajeEmergente("Registro", "Registro de Alumno exitoso!!!");
            }
       
            //limpiar vista 
            jTextFieldCodigo.setText("");
            jTextFieldNombre.setText("");
            jTextFieldPromedio.setText("");
            jTextFieldSemestre.setText("");
        }else{
           
           mostrarMensajeEmergente("Error", "No puedes tener espacios en blanco");
           
       }  
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void revisarCodigoRepetido(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_revisarCodigoRepetido
        if(jTextFieldCodigo.getText().equals(""))
            jTextFieldCodigo.setBackground(Color.red);
        else
            jTextFieldCodigo.setBackground(Color.white);
    }//GEN-LAST:event_revisarCodigoRepetido

    public static void mostrarMensajeEmergente(String titulo, String mensaje){
    
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.OK_OPTION);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> carrerasComboBox;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPromedio;
    private javax.swing.JTextField jTextFieldSemestre;
    // End of variables declaration//GEN-END:variables
}
